### ISSUE TITLE
Failed to activate the require-anywhere package

### ISSUE THREAD

**Issue by mohsenti** [ksxatompackages/require-anywhere#11] opened 2016-05-11 10:47 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: "Manjaro Linux"
**Thrown From**: [require-anywhere](https://github.com/ksxatompackages/require-anywhere) package, v1.1.3
### Stack Trace

Failed to activate the require-anywhere package

```
At Unexpected token =

SyntaxError: Unexpected token =
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at PureDeepIterable (/home/mohsen/.atom/packages/require-anywhere/node_modules/x-iterable/deep-iterable.js:5:29)
    at Object.<anonymous> (/home/mohsen/.atom/packages/require-anywhere/node_modules/x-iterable/deep-iterable.js:128:3)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at activate (/home/mohsen/.atom/packages/require-anywhere/index.js:8:22)
    at Object.module.exports.activate (/home/mohsen/.atom/packages/require-anywhere/index.js:59:21)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  2x -1:56.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:55.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:55.1.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:54 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:53.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:53.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:36.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.2.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -0:08.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:06.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:02.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:01.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:00.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
node-debugger, v1.5.1
nodejs-snippets, v2.0.0
require-anywhere, v1.1.3

# Dev
No dev packages
```

**Comment by KSXGitHub** [comment] 2016-05-11 14:46
I finally firgured out what causes the error: 

 * Short answer: Not really my fault, it's atom's fault, but I will fix it immediately.

 * Long answer: require-anywhere depends on a npm package called [x-iterable](https://www.npmjs.com/package/x-iterable)@">=2.4.5 <3.0.0". Recently, x-itevrable was updated to version >= 3.0.0 which requires full support of ECMAScript 6 syntax which atom currently doesn't supports (in this case: default parameter). While npm would installs x-iterable@2.4.5 if dependcy x-iterable is set to `">=2.4.5 <3.0.0"` in package.json, apm seems to be ignoring that, so it install lasted version 4.0.1 instead

**Comment by KSXGitHub** [comment] 2016-05-11 15:34
This bug has been fixed with version 2.0.0. Thanks for your report

**Closed as completed by KSXGitHub** 2016-05-11 15:34 UTC
Labels: bug

**Comment by acmoune** [comment] 2017-02-13 09:20
I am using v2.0.0 and I still have the same issue

**Comment by KSXGitHub** [comment] 2017-02-14 15:11
@acmoune Really? That's weird! Since I didn't see any error. Could you tell me how to reproduce the error?

For the time being, what this package does is basically adding things to `global.require.paths`, you can just add `global.require.paths.push('/path/to/your/node_modules')` to your init script (`init.coffee` or `init.js`) as an alternative.

**Comment by acmoune** [comment] 2017-02-16 14:20
@KSXGitHub it is OK, I misconfigured **paths.js**
